name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
#      Clone this repository
      - name: Check out this repository
        uses: actions/checkout@v4
        with:
          path: ./this-repository

#      Setup Java
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: 11

#     Build and Test this service
      - name: Build this project with Maven
        run: mvn --batch-mode --update-snapshots package  -f ./this-repository/pom.xml
